services:
  api:
    build:
      context: .
      additional_contexts:
        wdl_shared: ../wdl-shared
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "${API_EXPOSE_PORT:?API_EXPOSE_PORT is required}:8000"
    volumes:
      - ./src:/workspace/wdl-be-core/src
      - ./migrations:/workspace/wdl-be-core/migrations
      - ../wdl-shared/src:/workspace/wdl-shared/src
    networks:
      - vendor-network

networks:
  vendor-network:
    external: true
    name: vendor-network
